# Generated by Django 4.2.7 on 2024-04-24 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factory_contacts',
            options={'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.RemoveField(
            model_name='factory_contacts',
            name='name',
        ),
        migrations.AddField(
            model_name='factory_contacts',
            name='factory_name',
            field=models.CharField(default='', max_length=100, verbose_name='Название завода'),
        ),
        migrations.AddField(
            model_name='factory_contacts',
            name='house_number',
            field=models.CharField(default=0, max_length=100, verbose_name='номер дома'),
        ),
        migrations.AlterField(
            model_name='factory_contacts',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='factory_contacts',
            name='country',
            field=models.CharField(default='', max_length=100, verbose_name='страна'),
        ),
        migrations.AlterField(
            model_name='factory_contacts',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='factory_contacts',
            name='street',
            field=models.CharField(default='', max_length=100, verbose_name='улица'),
        ),
        migrations.CreateModel(
            name='Factory_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя продукта')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('date_launch', models.DateField(verbose_name='дата выхода продукта на рынок')),
                ('debt_to_supplier', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Задолженность перед поставщиком')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.factory_contacts', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
