# Generated by Django 4.2.7 on 2024-04-27 06:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0002_alter_factory_contacts_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory_product',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания'),
        ),
    ]
