# Generated by Django 4.2.7 on 2024-05-01 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0006_factory'),
        ('entrepreneur', '0005_alter_entrepreneur_provider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Factory_contacts',
        ),
        migrations.DeleteModel(
            name='Factory_product',
        ),
    ]
