# Generated by Django 4.2.7 on 2024-05-01 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneur', '0005_alter_entrepreneur_provider'),
        ('factory', '0007_delete_factory_contacts_delete_factory_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='provider',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='entrepreneur.entrepreneur', verbose_name='Поставщик'),
        ),
    ]
