# Generated by Django 4.2.7 on 2024-05-03 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0008_factory_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factory',
            name='provider',
        ),
    ]
