# Generated by Django 4.2.7 on 2024-05-01 13:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('country', models.CharField(default='', max_length=100, verbose_name='Страна')),
                ('city', models.CharField(default='', max_length=100, verbose_name='Город')),
                ('street', models.CharField(default='', max_length=100, verbose_name='Улица')),
                ('house_number', models.CharField(default=0, max_length=100, verbose_name='Номер дома')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя продукта')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('date_launch', models.DateField(verbose_name='Дата выхода продукта на рынок')),
                ('debt_to_supplier', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Задолженность перед поставщиком')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.DeleteModel(
            name='Entrepreneur_contacts',
        ),
        migrations.DeleteModel(
            name='Entrepreneur_product',
        ),
    ]
