# Generated by Django 4.2.7 on 2024-05-01 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0004_remove_factory_contacts_factory_name_and_more'),
        ('entrepreneur', '0002_contacts_product_delete_entrepreneur_contacts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='provider',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='factory.factory_contacts', verbose_name='Поставщик'),
        ),
    ]
