# Generated by Django 4.2.7 on 2024-04-26 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factory', '0002_alter_factory_contacts_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retail_network_contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retail_network_name', models.CharField(default='', max_length=100, verbose_name='Название завода')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('country', models.CharField(default='', max_length=100, verbose_name='страна')),
                ('city', models.CharField(default='', max_length=100, verbose_name='город')),
                ('street', models.CharField(default='', max_length=100, verbose_name='улица')),
                ('house_number', models.CharField(default=0, max_length=100, verbose_name='номер дома')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Retail_network_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя продукта')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('date_launch', models.DateField(verbose_name='дата выхода продукта на рынок')),
                ('debt_to_supplier', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Задолженность перед поставщиком')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.factory_contacts', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
