# Generated by Django 4.2.7 on 2024-04-27 06:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('retail_network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='retail_network_product',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='retail_network_contacts',
            name='retail_network_name',
            field=models.CharField(default='', max_length=100, verbose_name='Название сети'),
        ),
    ]
