# Generated by Django 4.2.7 on 2024-05-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_network', '0002_retail_network_product_creation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retail_network_contacts',
            name='retail_network_name',
        ),
        migrations.RemoveField(
            model_name='retail_network_product',
            name='provider',
        ),
        migrations.AddField(
            model_name='retail_network_contacts',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='retail_network_contacts',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='retail_network_contacts',
            name='country',
            field=models.CharField(default='', max_length=100, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='retail_network_contacts',
            name='house_number',
            field=models.CharField(default=0, max_length=100, verbose_name='Номер дома'),
        ),
        migrations.AlterField(
            model_name='retail_network_contacts',
            name='street',
            field=models.CharField(default='', max_length=100, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='retail_network_product',
            name='date_launch',
            field=models.DateField(verbose_name='Дата выхода продукта на рынок'),
        ),
    ]
