# Generated by Django 4.2.7 on 2024-05-01 14:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0007_delete_factory_contacts_delete_factory_product'),
        ('retail_network', '0004_rename_name_retail_network_product_name_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_contact', models.CharField(default='', max_length=100, verbose_name='Имя контакта')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('country', models.CharField(default='', max_length=100, verbose_name='Страна')),
                ('city', models.CharField(default='', max_length=100, verbose_name='Город')),
                ('street', models.CharField(default='', max_length=100, verbose_name='Улица')),
                ('house_number', models.CharField(default=0, max_length=100, verbose_name='Номер дома')),
                ('name_product', models.CharField(max_length=100, verbose_name='Имя продукта')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('date_launch', models.DateField(verbose_name='Дата выхода продукта на рынок')),
                ('debt_to_supplier', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Задолженность перед поставщиком')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания')),
                ('provider', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='factory.factory', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'розничная сеть',
                'verbose_name_plural': 'розничные сети',
            },
        ),
        migrations.DeleteModel(
            name='Retail_network_contacts',
        ),
        migrations.DeleteModel(
            name='Retail_network_product',
        ),
    ]
